# Generated by Django 3.1.4 on 2021-06-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpan', models.CharField(max_length=13)),
                ('meter_id', models.CharField(max_length=20)),
                ('meter_registration_id', models.CharField(max_length=3)),
                ('reading_date_time', models.CharField(max_length=20)),
                ('reading_register', models.CharField(max_length=20)),
                ('file_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
